version: '3.9'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - mongo
    env_file:
      - backend/docker-config.env
    ports:
      - "3000:3000"

  front-stops:
    build:
      context: front-stops
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
  
  mongo:
    image: mongo:5.0
    container_name: mongodb
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
