version: '3.9'

services:
  mongo:
    image: mongo:5.0
    container_name: mongodb
    volumes:
      - mongo-data:/data/db

  front-stops:
    build:
      context: front-stops
      dockerfile: Dockerfile

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - backend/docker-config.env
    depends_on:
      - mongo

  front-users:
    build:
      context: front-users
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - front-stops
      - backend

volumes:
  mongo-data:
